config/routes.rb
Rails.application.routes.draw do
  root 'dashboard#about'

  get '/team_members', to: 'dashboard#team_members'
  get '/about', to: 'dashboard#about'
  get '/dashboard', to: 'dashboard#index'
  get '/predict', to: 'dashboard#predict'
  get '/dataset_info', to: 'dashboard#dataset_info'

  get '/sales_intro', to: 'dashboard#sales_intro'
  get '/sales_conclusion', to: 'dashboard#sales_conclusion'

  get '/review_intro', to: 'dashboard#review_intro'
  get '/review_model_training', to: 'dashboard#review_model_training'
  get '/review_conclusion', to: 'dashboard#review_conclusion'

  get '/logistics_intro', to: 'dashboard#logistics_intro'
  get '/logistics_conclusion', to: 'dashboard#logistics_conclusion'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  layout 'dashboard'

  def index
    @dimension = params[:dimension] || 'week'
    @date_range = params[:date_range] || nil

    @orders = set_index_orders(@dimension, @date_range)
    @orders_payments_sum = @orders.map{|order| order.total_payment_value }.sum

    @sales_trend_chart_data        = set_sales_trend_chart_data(@orders, @dimension)
    @heat_map_chart_data           = set_heat_map_chart_data(@orders)
    @dount_chart_data              = set_dount_chart_data(@orders)
    @seller_rank_data              = set_seller_rank_data(@orders)
  end

  def team_members
  end

  def about
  end

  def predict
  end

  def dataset_info
  end

  # 銷售小組頁
  def sales_intro
  end

  def sales_conclusion
  end

  # 評價小組頁
  def review_intro
  end

  def review_model_training
  end

  def review_conclusion
  end

  # 物流小組頁
  def logistics_intro
  end

  def logistics_conclusion
  end

  private

    def set_index_orders(dimension, date_range)
      return Order.where(order_purchase_year: '2017')         if dimension == 'year'  && !date_range
      return Order.where(order_purchase_year_month: '201712') if dimension == 'month' && !date_range
      return Order.where(order_purchase_yearweek: '201748')   if dimension == 'week'  && !date_range

      return Order.where(order_purchase_year: date_range)       if dimension == 'year'  && date_range
      return Order.where(order_purchase_year_month: date_range) if dimension == 'month' && date_range
      return Order.where(order_purchase_yearweek: date_range)   if dimension == 'week'  && date_range

      return []
    end

    # 圖表 data: 銷售趨勢
    def set_sales_trend_chart_data(orders, dimension)
      columns = case dimension
        when 'year'
          orders.map{|p| p.order_purchase_month }.uniq.sort
        when 'month'
          orders.map{|p| p.order_purchase_date }.uniq.sort
        when 'week'
          orders.map{|p| p.order_purchase_dayofweek }.uniq.sort
        end

      data = []
      columns.each do |column|
        value = case dimension
        when 'year'
          orders.filter{|p| p.order_purchase_month == column }.sum(&:total_payment_value)
        when 'month'
          orders.filter{|p| p.order_purchase_date == column }.sum(&:total_payment_value)
        when 'week'
          orders.filter{|p| p.order_purchase_dayofweek == column }.sum(&:total_payment_value)
        end

        data << { country: set_column_name(column, dimension), visits: value }
      end

      return data.to_json
    end

    # 圖表 data: 購買頻率(依時間)
    def set_heat_map_chart_data(orders)
      return [
        {
          "hour": "12pm",
          "weekday": "Sun",
          "value": orders.filter{ |order| order.order_purchase_hour == 0 && order.order_purchase_dayofweek == 0}.count
        },
        {
          "hour": "1am",
          "weekday": "Sun",
          "value": orders.filter{ |order| order.order_purchase_hour == 1 && order.order_purchase_dayofweek == 0}.count
        },
        {
          "hour": "2am",
          "weekday": "Sun",
          "value": orders.filter{ |order| order.order_purchase_hour == 2 && order.order_purchase_dayofweek == 0}.count
        },
        {
          "hour": "3am",
          "weekday": "Sun",
          "value": orders.filter{ |order| order.order_purchase_hour == 3 && order.order_purchase_dayofweek == 0}.count
        },
        {
          "hour": "4am",
          "weekday": "Sun",
          "value": orders.filter{ |order| order.order_purchase_hour == 4 && order.order_purchase_dayofweek == 0}.count
        },
        {
          "hour": "5am",
          "weekday": "Sun",
          "value": orders.filter{ |order| order.order_purchase_hour == 5 && order.order_purchase_dayofweek == 0}.count
        },
        {
          "hour": "6am",
          "weekday": "Sun",
          "value": orders.filter{ |order| order.order_purchase_hour == 6 && order.order_purchase_dayofweek == 0}.count
        },
        {
          "hour": "7am",
          "weekday": "Sun",
          "value": orders.filter{ |order| order.order_purchase_hour == 7 && order.order_purchase_dayofweek == 0}.count
        },
        {
          "hour": "8am",
          "weekday": "Sun",
          "value": orders.filter{ |order| order.order_purchase_hour == 8 && order.order_purchase_dayofweek == 0}.count
        },
        {
          "hour": "9am",
          "weekday": "Sun",
          "value": orders.filter{ |order| order.order_purchase_hour == 9 && order.order_purchase_dayofweek == 0}.count
        },
        {
          "hour": "10am",
          "weekday": "Sun",
          "value": orders.filter{ |order| order.order_purchase_hour == 10 && order.order_purchase_dayofweek == 0}.count
        },
        {
          "hour": "11am",
          "weekday": "Sun",
          "value": orders.filter{ |order| order.order_purchase_hour == 11 && order.order_purchase_dayofweek == 0}.count
        },
        {
          "hour": "12am",
          "weekday": "Sun",
          "value": orders.filter{ |order| order.order_purchase_hour == 12 && order.order_purchase_dayofweek == 0}.count
        },
        {
          "hour": "1pm",
          "weekday": "Sun",
          "value": orders.filter{ |order| order.order_purchase_hour == 13 && order.order_purchase_dayofweek == 0}.count
        },
        {
          "hour": "2pm",
          "weekday": "Sun",
          "value": orders.filter{ |order| order.order_purchase_hour == 14 && order.order_purchase_dayofweek == 0}.count
        },
        {
          "hour": "3pm",
          "weekday": "Sun",
          "value": orders.filter{ |order| order.order_purchase_hour == 15 && order.order_purchase_dayofweek == 0}.count
        },
        {
          "hour": "4pm",
          "weekday": "Sun",
          "value": orders.filter{ |order| order.order_purchase_hour == 16 && order.order_purchase_dayofweek == 0}.count
        },
        {
          "hour": "5pm",
          "weekday": "Sun",
          "value": orders.filter{ |order| order.order_purchase_hour == 17 && order.order_purchase_dayofweek == 0}.count
        },
        {
          "hour": "6pm",
          "weekday": "Sun",
          "value": orders.filter{ |order| order.order_purchase_hour == 18 && order.order_purchase_dayofweek == 0}.count
        },
        {
          "hour": "7pm",
          "weekday": "Sun",
          "value": orders.filter{ |order| order.order_purchase_hour == 19 && order.order_purchase_dayofweek == 0}.count
        },
        {
          "hour": "8pm",
          "weekday": "Sun",
          "value": orders.filter{ |order| order.order_purchase_hour == 20 && order.order_purchase_dayofweek == 0}.count
        },
        {
          "hour": "9pm",
          "weekday": "Sun",
          "value": orders.filter{ |order| order.order_purchase_hour == 21 && order.order_purchase_dayofweek == 0}.count
        },
        {
          "hour": "10pm",
          "weekday": "Sun",
          "value": orders.filter{ |order| order.order_purchase_hour == 22 && order.order_purchase_dayofweek == 0}.count
        },
        {
          "hour": "11pm",
          "weekday": "Sun",
          "value": orders.filter{ |order| order.order_purchase_hour == 23 && order.order_purchase_dayofweek == 0}.count
        },

        # Mon ---------
        {
          "hour": "12pm",
          "weekday": "Mon",
          "value": orders.filter{ |order| order.order_purchase_hour == 0 && order.order_purchase_dayofweek == 1}.count
        },
        {
          "hour": "1am",
          "weekday": "Mon",
          "value": orders.filter{ |order| order.order_purchase_hour == 1 && order.order_purchase_dayofweek == 1}.count
        },
        {
          "hour": "2am",
          "weekday": "Mon",
          "value": orders.filter{ |order| order.order_purchase_hour == 2 && order.order_purchase_dayofweek == 1}.count
        },
        {
          "hour": "3am",
          "weekday": "Mon",
          "value": orders.filter{ |order| order.order_purchase_hour == 3 && order.order_purchase_dayofweek == 1}.count
        },
        {
          "hour": "4am",
          "weekday": "Mon",
          "value": orders.filter{ |order| order.order_purchase_hour == 4 && order.order_purchase_dayofweek == 1}.count
        },
        {
          "hour": "5am",
          "weekday": "Mon",
          "value": orders.filter{ |order| order.order_purchase_hour == 5 && order.order_purchase_dayofweek == 1}.count
        },
        {
          "hour": "6am",
          "weekday": "Mon",
          "value": orders.filter{ |order| order.order_purchase_hour == 6 && order.order_purchase_dayofweek == 1}.count
        },
        {
          "hour": "7am",
          "weekday": "Mon",
          "value": orders.filter{ |order| order.order_purchase_hour == 7 && order.order_purchase_dayofweek == 1}.count
        },
        {
          "hour": "8am",
          "weekday": "Mon",
          "value": orders.filter{ |order| order.order_purchase_hour == 8 && order.order_purchase_dayofweek == 1}.count
        },
        {
          "hour": "9am",
          "weekday": "Mon",
          "value": orders.filter{ |order| order.order_purchase_hour == 9 && order.order_purchase_dayofweek == 1}.count
        },
        {
          "hour": "10am",
          "weekday": "Mon",
          "value": orders.filter{ |order| order.order_purchase_hour == 10 && order.order_purchase_dayofweek == 1}.count
        },
        {
          "hour": "11am",
          "weekday": "Mon",
          "value": orders.filter{ |order| order.order_purchase_hour == 11 && order.order_purchase_dayofweek == 1}.count
        },
        {
          "hour": "12am",
          "weekday": "Mon",
          "value": orders.filter{ |order| order.order_purchase_hour == 12 && order.order_purchase_dayofweek == 1}.count
        },
        {
          "hour": "1pm",
          "weekday": "Mon",

app/views/shared/dashboard/_footer.html.erb
<footer id="footer" class="footer">
  <div class="copyright">
    &copy; Copyright <strong><span>AllenCheng</span></strong>. All Rights Reserved
  </div>
  <div class="credits">
    Template from <a href="https://bootstrapmade.com/nice-admin-bootstrap-admin-html-template/">NiceAdmin</a>
  </div>
</footer>

app/views/shared/dashboard/_header.html.erb
<!-- ======= Header ======= -->
<header id="header" class="header fixed-top d-flex align-items-center">

  <div class="d-flex align-items-center justify-content-between">
    <a href="<%= root_path %>" class="logo d-flex align-items-center">
      <img src="dashboard/assets/img/logo.png" alt="">
      <span class="d-none d-lg-block">大數據分析 - 電商組</span>
    </a>
    <i class="bi bi-list toggle-sidebar-btn"></i>
  </div><!-- End Logo -->


  <nav class="header-nav ms-auto">
    <ul class="d-flex align-items-center">

      <li class="nav-item dropdown">

        <a class="nav-link nav-icon" href="#" data-bs-toggle="dropdown">
          <i class="bi bi-chat-left-text"></i>
          <span class="badge bg-success badge-number">3</span>
        </a><!-- End Messages Icon -->

        <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow messages" style="width: 300px">
          <li class="message-item">
            <a href="/sales_intro">
              <img src="dashboard/assets/img/ice.png" alt="" class="rounded-circle">
              <div>
                <h4>銷售小組</h4>
                <p>我們找到造成營業額差距的關鍵因子 推論出精準行銷的依據 ... <span style="font-size: 4px;color: #c9c9c9;">(瞭解更多)</span></p>
                <p style="font-size: 10px;color: #c9c9c9">來自 偉祥、雪樺與儒育</p>
              </div>
            </a>
          </li>
          <li>
            <hr class="dropdown-divider">
          </li>

          <li class="message-item">
            <a href="/review_intro">
              <img src="dashboard/assets/img/anita.png" alt="" class="rounded-circle">
              <div>
                <h4>評價小組</h4>
                <p>準備了很精彩的報告: 預測評價的好壞，做為平台篩選新進賣家販售商品的依據 ... <span style="font-size: 4px;color: #c9c9c9;">(瞭解更多)</span></p>
                <p style="font-size: 10px;color: #c9c9c9">來自 怡家與智弘</p>
              </div>
            </a>
          </li>
          <li>
            <hr class="dropdown-divider">
          </li>

          <li class="message-item">
            <a href="/logistics_intro">
              <img src="dashboard/assets/img/angela.png" alt="" class="rounded-circle">
              <div>
                <h4>物流小組</h4>
                <p>敬請欣賞我們精心準備的研究，並提供了完整的模型程式碼與調教歷程 ... <span style="font-size: 4px;color: #c9c9c9;">(瞭解更多)</span></p>
                <p style="font-size: 10px;color: #c9c9c9">來自 舜華、怡文與偉鑅</p>
              </div>
            </a>
          </li>
        </ul><!-- End Messages Dropdown Items -->

      </li><!-- End Messages Nav -->

      <li class="nav-item dropdown pe-3">

        <a class="nav-link nav-profile d-flex align-items-center pe-0" href="#" data-bs-toggle="dropdown">
          <img src="dashboard/assets/img/allen.png" alt="Profile" class="rounded-circle">
          <span class="d-none d-md-block dropdown-toggle ps-2">Allen Cheng</span>
        </a><!-- End Profile Iamge Icon -->

        <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow profile">
          <li class="dropdown-header">
            <h6>Allen Cheng</h6>
            <span>Web Designer</span>
          </li>
          <li>
            <hr class="dropdown-divider">
          </li>

          <li>
            <a class="dropdown-item d-flex align-items-center" href="<%= about_path %>">
              <i class="bi bi-exclamation-square"></i>
              <span>關於專題</span>
            </a>
          </li>
          <li>
            <hr class="dropdown-divider">
          </li>

          <li>
            <a class="dropdown-item d-flex align-items-center" href="<%= team_members_path %>">
              <i class="bi bi-person"></i>
              <span>成員介紹</span>
            </a>
          </li>
          <li>
            <hr class="dropdown-divider">
          </li>

          <li>
            <a class="dropdown-item d-flex align-items-center" href="<%= dataset_info_path %>">
              <i class="bi bi-server"></i>
              <span>背景資料概述</span>
            </a>
          </li>

        </ul><!-- End Profile Dropdown Items -->
      </li><!-- End Profile Nav -->

    </ul>
  </nav><!-- End Icons Navigation -->

</header><!-- End Header -->

app/views/shared/dashboard/_sidebar.html.erb
<!-- ======= Sidebar ======= -->
<aside id="sidebar" class="sidebar">

  <ul class="sidebar-nav" id="sidebar-nav">

    <li class="nav-item">
      <a class="nav-link <%= 'collapsed' if !current_page?(root_path) %>" href="<%= root_path %>">
        <i class="bi bi-exclamation-square"></i>
        <span>關於專題</span>
      </a>
    </li>

    <li class="nav-item">
      <a class="nav-link <%= 'collapsed' if !current_page?(team_members_path) %>" href="<%= team_members_path %>">
        <i class="bi bi-person"></i>
        <span>成員介紹</span>
      </a>
    </li>

    <li class="nav-item">
      <a class="nav-link <%= 'collapsed' if !current_page?(dataset_info_path) %>" href="<%= dataset_info_path %>">
        <i class="bi bi-server"></i>
        <span>資料背景概述</span>
      </a>
    </li>

    <li class="nav-item">
      <a class="nav-link <%= 'collapsed' if !current_page?(dashboard_path) %>" href="<%= dashboard_path %>">
        <i class="bi bi-grid"></i>
        <span>Dashboard</span>
      </a>
    </li>

    <li class="nav-item">
      <a class="nav-link <%= 'collapsed' if !(current_page?('/sales_intro') || current_page?('/sales_core_model') || current_page?('/sales_model_training') || current_page?('/sales_conclusion')) %>" data-bs-target="#sales" data-bs-toggle="collapse" href="#">
        <i class="bi bi-bag-check-fill"></i><span>專題: 銷售小組</span><i class="bi bi-chevron-down ms-auto"></i>
      </a>
      <ul id="sales" class="nav-content collapse <%= 'show' if current_page?('/sales_intro') || current_page?('/sales_core_model') || current_page?('/sales_model_training') || current_page?('/sales_conclusion') %>" data-bs-parent="#sidebar-nav">
        <li>
          <a href="/sales_intro" class="<%= 'active' if current_page?('/sales_intro') %>">
            <i class="bi bi-file-earmark-font"></i><span>研究摘要(目的與動機)</span>
          </a>
        </li>
        <li>
          <a target="_blank" href="https://ec-study.allen-cheng.com/datasets/sales_model_training_3.pdf">
            <i class="bi bi-lightning"></i><span>模型調校歷程&nbsp;&nbsp;<i class="bi bi-arrow-up-right-square" style="font-size: 10px;"></i></span>
          </a>
        </li>
        <li>
          <a href="/sales_conclusion" class="<%= 'active' if current_page?('/sales_conclusion') %>">
            <i class="bi bi-check2-square"></i><span>管理意涵與營運策略</span>
          </a>
        </li>
        <li>
          <a target="_blank" href="https://colab.research.google.com/drive/1gC92Upcka5wAzYh2HQAQkFxxO7fhs0uI?usp=sharing">
            <i class="bi bi-code-slash"></i><span>模型程式碼 &nbsp;&nbsp;<i class="bi bi-arrow-up-right-square" style="font-size: 10px;"></i></span>
          </a>
        </li>
      </ul>
    </li><!-- End Tables Nav -->

    <li class="nav-item">
      <a class="nav-link  <%= 'collapsed' if !(current_page?('/logistics_intro') || current_page?('/logistics_core_model') || current_page?('/logistics_model_training') || current_page?('/logistics_conclusion')) %>" data-bs-target="#logistics" data-bs-toggle="collapse" href="#">
        <i class="bi bi-pin-map-fill"></i><span>專題: 物流小組</span><i class="bi bi-chevron-down ms-auto"></i>
      </a>
      <ul id="logistics" class="nav-content collapse <%= 'show' if current_page?('/logistics_intro') || current_page?('/logistics_core_model') || current_page?('/logistics_model_training') || current_page?('/logistics_conclusion') %>" data-bs-parent="#sidebar-nav">
        <li>
          <a href="/logistics_intro" class="<%= 'active' if current_page?('/logistics_intro') %>">
            <i class="bi bi-file-earmark-font"></i><span>研究摘要(目的與動機)</span>
          </a>
        </li>
        <li>
          <a href="/logistics_conclusion" class="<%= 'active' if current_page?('/logistics_conclusion') %>">
            <i class="bi bi-check2-square"></i><span>管理意涵與營運策略</span>
          </a>
        </li>
        <li>
          <a target="_blank" href="https://colab.research.google.com/drive/1eXcXfND8WD1_hEOyBh_TkqkY5Vb3CIvV?usp=sharing">
            <i class="bi bi-code-slash"></i><span>模型程式碼(final)&nbsp;&nbsp;<i class="bi bi-arrow-up-right-square" style="font-size: 10px;"></i></span>
          </a>
        </li>
      </ul>
    </li><!-- End Icons Nav -->

    <li class="nav-item">
      <a class="nav-link <%= 'collapsed' if !(current_page?('/review_intro') || current_page?('/review_core_model') || current_page?('/review_model_training') || current_page?('/review_conclusion')) %>" data-bs-target="#review" data-bs-toggle="collapse" href="#">
        <i class="bi bi-emoji-heart-eyes"></i><span>專題: 評價小組</span><i class="bi bi-chevron-down ms-auto"></i>
      </a>
      <ul id="review" class="nav-content collapse <%= 'show' if current_page?('/review_intro') || current_page?('/review_core_model') || current_page?('/review_model_training') || current_page?('/review_conclusion') %>" data-bs-parent="#sidebar-nav">
        <li>
          <a href="/review_intro" class="<%= 'active' if current_page?('/review_intro') %>">
            <i class="bi bi-file-earmark-font"></i><span>研究摘要(目的與動機)</span>
          </a>
        </li>
        <li>
          <a target="_blank" href="https://ec-study.allen-cheng.com/datasets/review_model_training_2.pdf">
            <i class="bi bi-lightning"></i><span>模型調校歷程 &nbsp;&nbsp;<i class="bi bi-arrow-up-right-square" style="font-size: 10px;"></i></span>
          </a>
        </li>
        <li>
          <a href="/review_conclusion" class="<%= 'active' if current_page?('/review_conclusion') %>">
            <i class="bi bi-check2-square"></i><span>管理意涵與營運策略</span>
          </a>
        </li>
        <li>
          <a target="_blank" href="https://colab.research.google.com/drive/1wLfTKu-EJNwVD0xtQDnnDpq05urJk1u7?usp=sharing">
            <i class="bi bi-code-slash"></i><span>模型程式碼 &nbsp;&nbsp;<i class="bi bi-arrow-up-right-square" style="font-size: 10px;"></i></span>
          </a>
        </li>
      </ul>
    </li><!-- End Charts Nav -->


    <li class="nav-item">
      <a class="nav-link collapsed" href="https://github.com/allenCheng1984/ec_study" target="_blank">
        <i class="bi bi-github"></i>
        <span>網站程式碼 &nbsp;&nbsp;<i class="bi bi-arrow-up-right-square" style="font-size: 10px;"></i></span>
      </a>
    </li>

    <li class="nav-item">
      <a class="nav-link collapsed" href="https://ec-study.allen-cheng.com/datasets/ec-study-slides_4.pdf" target="_blank">
        <i class="bi bi-file-earmark-slides"></i>
        <span>專題簡報 &nbsp;&nbsp;<i class="bi bi-arrow-up-right-square" style="font-size: 10px;"></i></span>
      </a>
    </li>

  </ul>

</aside><!-- End Sidebar-->